<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">LPPM UIN SUSKA</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div>
                <h4 class="page-title">Dashboard</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

<!--    <div class="row">-->
<!--        <div class="col-xl-4">-->
<!--            <div class="card card-body">-->
<!--                <h4 class="card-title">KKN ONLINE</h4>-->
<!--                <p class="card-text">Sistem Informasi KKN Online</p>-->
<!--                <p class="card-text">-->
<!--                    <small class="text-muted"><button class="btn btn-warning btn-block">GO</button></small>-->
<!--                </p>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-xl-4">-->
<!--            <div class="card card-body">-->
<!--                <h4 class="card-title">ABSEN ONLINE</h4>-->
<!--                <p class="card-text">Absen Online Berbasi Android & Web</p>-->
<!--                <p class="card-text">-->
<!--                    <small class="text-muted"><button class="btn btn-success btn-block">GO</button></small>-->
<!--                </p>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-xl-4">-->
<!--            <div class="card card-body">-->
<!--                <h4 class="card-title">E - Office</h4>-->
<!--                <p class="card-text">Aplikasi E - Office Internal LPPM</p>-->
<!--                <p class="card-text">-->
<!--                    <small class="text-muted"><button class="btn btn-purple btn-block">GO</button></small>-->
<!--                </p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <div class="row">

        <div class="col-xl-3 col-md-6">
            <div class="card-box">
                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                        <i class="mdi mdi-dots-vertical"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Another action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Something else</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
                    </div>
                </div>

                <h4 class="header-title mt-0 mb-4">Mahasiswa</h4>

                <div class="widget-chart-1">
                    <div class="widget-chart-box-1 float-left" dir="ltr">
                        <span class="fa fa-users fa-5x text-primary"></span>
                    </div>

                    <div class="widget-detail-1 text-right">
                        <h2 class="font-weight-normal pt-2 mb-1"> <?= $mahasiswa ?> </h2>
                        <p class="text-muted mb-1">Total Mahasiswa</p>
                    </div>
                </div>
            </div>

        </div><!-- end col -->

        <div class="col-xl-3 col-md-6">
            <div class="card-box">
                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                        <i class="mdi mdi-dots-vertical"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Another action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Something else</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
                    </div>
                </div>

                <h4 class="header-title mt-0 mb-4">Kelompok KKN</h4>

                <div class="widget-chart-1">
                    <div class="widget-chart-box-1 float-left" dir="ltr">
                        <span class="fa fa-users fa-5x text-success"></span>
                    </div>

                    <div class="widget-detail-1 text-right">
                        <h2 class="font-weight-normal pt-2 mb-1"> <?= $kelompok ?> </h2>
                        <p class="text-muted mb-1">Total Kelompok</p>
                    </div>
                </div>
            </div>

        </div><!-- end col -->

        <div class="col-xl-3 col-md-6">
            <div class="card-box">
                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                        <i class="mdi mdi-dots-vertical"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Another action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Something else</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
                    </div>
                </div>

                <h4 class="header-title mt-0 mb-4">Mahasiswa Laki-Laki</h4>

                <div class="widget-chart-1">
                    <div class="widget-chart-box-1 float-left" dir="ltr">
                        <span class="fa fa-users fa-5x text-dark"></span>
                    </div>
                    <div class="widget-chart-1">


                        <div class="widget-detail-1 text-right">
                            <h2 class="font-weight-normal pt-2 mb-1"> <?= $mhs[0]['jumlah'] ?> </h2>
                            <p class="text-muted mb-1">Total Laki-Laki</p>
                        </div>
                    </div>
                </div>
            </div>

        </div><!-- end col -->

        <div class="col-xl-3 col-md-6">
            <div class="card-box">
                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                        <i class="mdi mdi-dots-vertical"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Another action</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Something else</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
                    </div>
                </div>

                <h4 class="header-title mt-0 mb-4">Mahasiswa Perempuan</h4>

                <div class="widget-box-2">
                    <div class="widget-chart-box-1 float-left" dir="ltr">
                        <span class="fa fa-users fa-5x text-pink"></span>
                    </div>
                    <div class="widget-chart-1">

                        <div class="widget-detail-1 text-right">
                            <h2 class="font-weight-normal pt-2 mb-1"> <?= $mhs[1]['jumlah'] ?> </h2>
                            <p class="text-muted mb-1">Total Perempuan</p>
                        </div>
                    </div>
                </div>
            </div>

        </div><!-- end col -->

    </div>

</div> <!-- end container -->
