<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <?= $this->tag->getTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="LPPM UIN SUSKA" name="description"/>
    <meta content="LPPM UIN SUSKA" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="<?= $this->url->get('img/logo.jpg') ?>">

    <?php
    echo $this->tag->stylesheetLink("assets/libs/datatables/dataTables.bootstrap4.css");
    echo $this->tag->stylesheetLink("assets/libs/datatables/responsive.bootstrap4.css");
    echo $this->tag->stylesheetLink("assets/libs/datatables/buttons.bootstrap4.css");
    echo $this->tag->stylesheetLink("assets/libs/datatables/select.bootstrap4.css");
    echo $this->tag->stylesheetLink('assets/libs/morris-js/morris.css');
    echo $this->tag->stylesheetLink('assets/libs/bootstrap-datepicker/bootstrap-datepicker.css');
    echo $this->tag->stylesheetLink('assets/css/bootstrap.min.css');
    echo $this->tag->stylesheetLink('css/pe-icon-7.css');
    echo $this->tag->stylesheetLink('assets/css/icons.min.css');
    echo $this->tag->stylesheetLink('assets/css/app.min.css');
    echo $this->tag->javascriptInclude('assets/js/vendor.min.js');
    echo $this->tag->javascriptInclude('assets/libs/jquery-knob/jquery.knob.min.js');
    ?>
    <script>
        const baseUrl = '<?= $this->url->get() ?>';
    </script>
</head>

<body>

<!-- Navigation Bar-->
<header id="topnav">

    <!-- Topbar Start -->
    <div class="navbar-custom">
        <div class="container-fluid">
            <ul class="list-unstyled topnav-menu float-right mb-0">

                <li class="dropdown notification-list">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle nav-link">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </li>

                <li class="d-none d-sm-block">
                    <form class="app-search">
                        <div class="app-search-box">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search...">
                                <div class="input-group-append">
                                    <button class="btn" type="submit">
                                        <i class="fe-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </li>

                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle waves-effect" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="false" aria-expanded="false">
                        <i class="fe-bell noti-icon"></i>
                        <span class="badge badge-danger rounded-circle noti-icon-badge">9</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-lg">

                        <!-- item-->
                        <div class="dropdown-item noti-title">
                            <h5 class="m-0">
                                <span class="float-right">
                                    <a href="" class="text-dark">
                                        <small>Clear All</small>
                                    </a>
                                </span>Notification
                            </h5>
                        </div>

                        <div class="slimscroll noti-scroll">

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item active">
                                <div class="notify-icon">
                                    <img src="assets/images/users/user-1.jpg" class="img-fluid rounded-circle" alt=""/>
                                </div>
                                <p class="notify-details">Cristina Pride</p>
                                <p class="text-muted mb-0 user-msg">
                                    <small>Hi, How are you? What about our next meeting</small>
                                </p>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <div class="notify-icon bg-primary">
                                    <i class="mdi mdi-comment-account-outline"></i>
                                </div>
                                <p class="notify-details">Caleb Flakelar commented on Admin
                                    <small class="text-muted">1 min ago</small>
                                </p>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <div class="notify-icon">
                                    <img src="assets/images/users/user-4.jpg" class="img-fluid rounded-circle" alt=""/>
                                </div>
                                <p class="notify-details">Karen Robinson</p>
                                <p class="text-muted mb-0 user-msg">
                                    <small>Wow ! this admin looks good and awesome design</small>
                                </p>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <div class="notify-icon bg-warning">
                                    <i class="mdi mdi-account-plus"></i>
                                </div>
                                <p class="notify-details">New user registered.
                                    <small class="text-muted">5 hours ago</small>
                                </p>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <div class="notify-icon bg-info">
                                    <i class="mdi mdi-comment-account-outline"></i>
                                </div>
                                <p class="notify-details">Caleb Flakelar commented on Admin
                                    <small class="text-muted">4 days ago</small>
                                </p>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <div class="notify-icon bg-secondary">
                                    <i class="mdi mdi-heart"></i>
                                </div>
                                <p class="notify-details">Carlos Crouch liked
                                    <b>Admin</b>
                                    <small class="text-muted">13 days ago</small>
                                </p>
                            </a>
                        </div>

                        <!-- All-->
                        <a href="javascript:void(0);"
                           class="dropdown-item text-center text-primary notify-item notify-all">
                            View all
                            <i class="fi-arrow-right"></i>
                        </a>

                    </div>
                </li>

                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#"
                       role="button" aria-haspopup="false" aria-expanded="false">
                        <img src="<?= $this->url->get('img/user1_128.png') ?>" alt="user-image" class="rounded-circle">
                        <span class="pro-user-name ml-1 text-capitalize">
                                    <?= $this->session->get('AUTH_NAME') ?>
                            <i class="mdi mdi-chevron-down"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                        <!-- item-->
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome !</h6>
                        </div>

                        <!-- item-->
                        <a href="<?= $this->url->get('mahasiswa/data-diri') ?>" class="dropdown-item notify-item">
                            <i class="fe-user"></i>
                            <span>Data Diri</span>
                        </a>

                        <div class="dropdown-divider"></div>

                        <!-- item-->
                        <a href="<?= $this->url->get('proses/keluar') ?>" class="dropdown-item notify-item">
                            <i class="fe-log-out"></i>
                            <span>Logout</span>
                        </a>

                    </div>
                </li>

                <li class="dropdown notification-list">
                    <a href="javascript:void(0);" class="nav-link right-bar-toggle waves-effect">
                        <i class="fe-settings noti-icon"></i>
                    </a>
                </li>

            </ul>

            <!-- LOGO -->
            <div class="logo-box">
                <a href="<?= $this->url->get('dashboard/admin/manage') ?>" class="logo text-center">
                    <span class="logo-lg">
                        <img src="<?= $this->url->get('img/uinsuska.png') ?>" alt="" height="40">
                         <span class="logo-lg-text-light"
                               style="font-size: 18px">LPPM Lembaga Penelitian dan Pengabdian</span>
                    </span>
                    <span class="logo-sm">
                        <!-- <span class="logo-sm-text-dark">U</span> -->
                        <!--                        <img src="assets/images/logo-sm.png" alt="" height="24">-->
                    </span>
                </a>
            </div>

        </div> <!-- end container-fluid-->
    </div>
    <!-- end Topbar -->

    <div class="topbar-menu">
        <div class="container-fluid">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu">

                    <li class="has-submenu">
                        <a href="<?= $this->url->get('dashboard/admin/manage') ?>"><i
                                    class="mdi mdi-view-dashboard"></i>Dashboard</a>
                    </li>

                    <!--  <li class="has-submenu">
                        <a href="#"> <i class="mdi mdi-invert-colors"></i>Data Master
                            <div class="arrow-down"></div>
                        </a>
                        <ul class="submenu">
                            <li>
                                <ul>
                                    <li>
                                        <a href="<?php /*$this->url->get('setting/admin/manage') */ ?>">Setting</a>
                                    </li>
                                    <li>
                                        <a href="<?php /*$this->url->get('fakultas/admin/manage') */ ?>">Data Fakultas</a>
                                    </li>
                                    <li>
                                        <a href="<?php /*$this->url->get('jurusan/admin/manage') */ ?>">Data Jurusan</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>-->
                    <?php if ($this->session->get('AUTH_ROLE') == 'Root'): ?>
                        <li class="has-submenu">
                            <a href="<?= $this->url->get('mahasiswa/admin/manage') ?>">Data Mahasiswa</a>
                        </li>
                        <li class="has-submenu">
                            <a href="<?= $this->url->get('dosen/admin/manage') ?>">Data Dosen</a>
                        </li>
                        <li class="has-submenu">
                            <a href="<?= $this->url->get('mahasiswa/admin/kelompok') ?>">Data Kelompok</a>
                        </li>
                        <li class="has-submenu">
                            <a href="<?= $this->url->get('laporan/admin/laporan') ?>">Laporan</a>
                        </li>
                        <li class="has-submenu">
                            <a href="<?= $this->url->get('admin/kegiatan') ?>">Kegiatan KKN</a>
                        </li>
                    <?php else: ?>
                        <li class="has-submenu">
                            <a href="<?= $this->url->get('mahasiswa/kegiatan/kkn') ?>">Kegiatan KKN</a>
                        </li>
                        <li class="has-submenu">
                            <a href="<?= $this->url->get('mahasiswa/kegiatan/upload') ?>">Upload Kegiatan KKN</a>
                        </li>
                    <?php endif; ?>
                </ul>
                <!-- End navigation menu -->

                <div class="clearfix"></div>
            </div>
            <!-- end #navigation -->
        </div>
        <!-- end container -->
    </div>
    <!-- end navbar-custom -->

</header>
<!-- End Navigation Bar-->

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="wrapper">
    <?= $this->getContent('') ?>
</div>
<!-- end wrapper -->

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <?= date('Y') ?> &copy; LPPM UIN SUSKA <a href="">AHMAD FAUZI RAHMAN S.T MTA</a>
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-sm-block">
                    <a href="javascript:void(0);">About Us</a>
                    <a href="javascript:void(0);">Help</a>
                    <a href="javascript:void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

<!-- Right Sidebar -->
<div class="right-bar">
    <div class="rightbar-title">
        <a href="javascript:void(0);" class="right-bar-toggle float-right">
            <i class="dripicons-cross noti-icon"></i>
        </a>
        <h4 class="m-0 text-white">Settings</h4>
    </div>
    <div class="slimscroll-menu rightbar-content">
        <!-- User box -->
        <div class="user-box">
            <div class="user-img">
                <img src="<?= $this->url->get('img/user1_128.png') ?>" alt="user-img" title="Mat Helme"
                     class="rounded-circle img-fluid">
                <a href="javascript:void(0);" class="user-edit"><i class="mdi mdi-pencil"></i></a>
            </div>

            <h5><a href="javascript: void(0);"><?= $this->session->get('AUTH_NAME') ?></a></h5>
            <p class="text-muted mb-0"><small><?= $this->session->get('AUTH_ROLE') ?></small></p>
        </div>

        <!-- Settings -->
        <hr class="mt-0"/>
        <h5 class="pl-3">Basic Settings</h5>
        <hr class="mb-0"/>

        <div class="p-3">
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox1" type="checkbox" checked>
                <label for="Rcheckbox1">
                    Notifications
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox2" type="checkbox" checked>
                <label for="Rcheckbox2">
                    API Access
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox3" type="checkbox">
                <label for="Rcheckbox3">
                    Auto Updates
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox4" type="checkbox" checked>
                <label for="Rcheckbox4">
                    Online Status
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-0">
                <input id="Rcheckbox5" type="checkbox" checked>
                <label for="Rcheckbox5">
                    Auto Payout
                </label>
            </div>
        </div>

        <!-- Timeline -->
        <hr class="mt-0"/>
        <h5 class="pl-3 pr-3">Messages <span class="float-right badge badge-pill badge-danger">25</span></h5>
        <hr class="mb-0"/>
        <div class="p-3">
            <div class="inbox-widget">
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-2.jpg" class="rounded-circle" alt="">
                    </div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Tomaslau</a></p>
                    <p class="inbox-item-text">I've finished it! See you so...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-3.jpg" class="rounded-circle" alt="">
                    </div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Stillnotdavid</a></p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-4.jpg" class="rounded-circle" alt="">
                    </div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Kurafire</a></p>
                    <p class="inbox-item-text">Nice to meet you</p>
                </div>

                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-5.jpg" class="rounded-circle" alt="">
                    </div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Shahedk</a></p>
                    <p class="inbox-item-text">Hey! there I'm available...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-6.jpg" class="rounded-circle" alt="">
                    </div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Adhamdannaway</a></p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
            </div> <!-- end inbox-widget -->
        </div> <!-- end .p-3-->

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>
<?php

echo $this->tag->javascriptInclude("js/bootstrap-notify.js");
echo $this->tag->javascriptInclude("assets/libs/datatables/jquery.dataTables.min.js");
echo $this->tag->javascriptInclude("assets/libs/datatables/dataTables.bootstrap4.js");
echo $this->tag->javascriptInclude("assets/libs/datatables/dataTables.responsive.min.js");
echo $this->tag->javascriptInclude("assets/libs/datatables/responsive.bootstrap4.min.js");
echo $this->tag->javascriptInclude("assets/libs/datatables/dataTables.buttons.min.js");
echo $this->tag->javascriptInclude("assets/libs/datatables/buttons.bootstrap4.min.js");
//echo $this->tag->javascriptInclude("assets/libs/datatables/buttons.html5.min.js");
//echo $this->tag->javascriptInclude("assets/libs/datatables/buttons.flash.min.js");
//echo $this->tag->javascriptInclude("assets/libs/datatables/buttons.print.min.js");
//echo $this->tag->javascriptInclude("assets/libs/datatables/dataTables.keyTable.min.js");
//echo $this->tag->javascriptInclude("assets/libs/datatables/dataTables.select.min.js");
//echo $this->tag->javascriptInclude("assets/libs/pdfmake/pdfmake.min.js");
//echo $this->tag->javascriptInclude("assets/libs/pdfmake/vfs_fonts.js");

echo $this->tag->javascriptInclude("assets/libs/bootstrap-datepicker/bootstrap-datepicker.min.js");
echo $this->tag->javascriptInclude("assets/js/pages/datatables.init.js");
echo $this->tag->javascriptInclude('assets/libs/morris-js/morris.min.js');
echo $this->tag->javascriptInclude('assets/libs/raphael/raphael.min.js');
echo $this->tag->javascriptInclude('js/keperluan.js');

echo $this->tag->javascriptInclude('assets/js/pages/dashboard.init.js');
//echo $this->tag->javascriptInclude('assets/js/pages/form-advanced.init.js');
?>
</body>
</html>